DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(100) NOT NULL,
	WDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM CALENDAR




ROW_NUMBER는 번호 주는 것
파티션바이는 묶어주는 것
첫번째 부터 여덟번째 전까지 YYYY MM DD
오름정력 1일 2일 3일 ~ 마지막날까지

7월달에 해당하는 것을 일변로 묶어라

SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(RDATE, 1, 8) ORDER BY RDATE ASC) RNUM,
	SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM CALENDAR
WHERE ID='1' AND SUBSTR(RDATE, 1, 6)='7'




하루에 최대 5개의 일정을 표현

SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM (SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(RDATE, 1, 8) ORDER BY RDATE ASC) RNUM,
	SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM CALENDAR
WHERE ID='111' AND SUBSTR(RDATE, 1, 7)='8')
WHERE RNUM BETWEEN 1 AND 5;




DELETE CALENDAR WHERE SEQ=13;

