CREATE TABLE MEMBER(
	ID VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20)
)

INSERT INTO MEMBER(ID, PASSWORD, NAME, EMAIL) VALUES('111', '111', '111', '111')
INSERT INTO MEMBER(ID, PASSWORD, NAME, EMAIL) VALUES('q', 'w', 'qw', 'qw')
INSERT INTO MEMBER(ID, PASSWORD, NAME, EMAIL) VALUES('abc', '123', 'name', 'email')
INSERT INTO MEMBER(ID, PASSWORD, NAME, EMAIL) VALUES('hi', 'hello', 'hiname', 'hiemail')

SELECT * FROM MEMBER
