DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PDS;

CREATE TABLE PDS(
	SEQ NUMBER(9) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	FILENAME VARCHAR2(50) NOT NULL,
	READCOUNT NUMBER(9) NOT NULL,
	DOWNCOUNT NUMBER(9) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_PDS
START WITH 1
INCREMENT BY 1;

ALTER TABLE PDS
ADD CONSTRAINT FK_PDS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM PDS


SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM(	SELECT ROW_NUMBER()OVER(ORDER BY RDATE) AS RNUM, SEQ, ID, TITLE, CONTENT, RDATE, WDATE
		FROM CALENDAR
		WHERE ID='1' AND RDATE='20190902'
	)
WHERE RNUM BETWEEN 1 AND 5





