-- 기본 함수

-- DUAL : 가상테이블 -> 결과 확인용 임시 테이블
SELECT 1 FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT '가' FROM DUAL;
SELECT 34*21 FROM DUAL;

-- 문자함수
-- CHR(N) : ASCII값을 해당되는 문자로 변환
SELECT CHR(97) FROM DUAL;
SELECT CHR(65) FROM DUAL;

-- "내 점수는 " + CHR(65) + "입니다"
SELECT '내 점수는 ' || CHR(65) || '입니다'
FROM DUAL;

-- LPAD(RPAD) : 나머지 빈칸을 특정문자 채운다
SELECT LPAD('BBB', 5) FROM DUAL;
SELECT LPAD('BBB', 5, '-') FROM DUAL;
SELECT LPAD('BBB', 5, '+') FROM DUAL;

-- INSTR == indexof 문자가 몇번째 있니?
-- 시작 java : 0 ~, oracle : 1 ~
SELECT INSTR('A123B456C', 'B') FROM DUAL;

SELECT INSTR('A123B456C789B', 'B', 7) FROM DUAL;
-- 7번째 이후부터 찾아 처음부터 몇번째인지

SELECT INSTR('A123B456C789B', 'B', 7, 1) FROM DUAL;
-- 7이후 1번째 B가 처음부터 몇번째인지
SELECT INSTR('A123B456C789B', 'B', 7, 2) FROM DUAL;
-- 7이후 2번째 B가 처음부터 몇번째인지

-- REPLACE : 문자열치환
SELECT REPLACE('AAAADRGABC', 'A', 'a') FROM DUAL;
SELECT REPLACE('AAAADRGABC', 'AAAA', 'a') FROM DUAL;

-- TRANSLATE : 문자치환
SELECT TRANSLATE('AAAADRGABC', 'A', 'a') FROM DUAL;
SELECT TRANSLATE('AAAADRGABC', 'AAAA', 'a') FROM DUAL;
-- TRANSLATE는 'AAAA'를 'A'로 인식하고 'a'로 변환
-- REPLACE는 'AAAA'를 'AAAA'로 인식하고 'a'로 변환

-- 숫자 함수
-- 올림
SELECT CEIL(13.1) FROM DUAL;

-- 내림
SELECT FLOOR(14.9) FROM DUAL;

-- 나눈 나머지
SELECT MOD(9.1, 2.3) FROM DUAL;

-- 승수
SELECT POWER(3, 2) FROM DUAL;

-- 반올림
SELECT ROUND(13.5) FROM DUAL;

-- 부호  +:1  0:0  -:-1
SELECT SIGN(13.4) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT SIGN(-23.5) FROM DUAL;

-- 버림
SELECT TRUNC(12.3456) FROM DUAL;
-- 소수점 버림
SELECT TRUNC(12.3456, 2) FROM DUAL;
-- 소수점 2자리 이후 버림
SELECT TRUNC(12.3456, -1) FROM DUAL;

-- ASCII CODE <-> CHR 문자를 ASCII값으로 변환
SELECT ASCII('A') FROM DUAL;

-- 변환 함수 DATE -> STRING
-- TO_CHAR
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD-HH-MI-SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') FROM DUAL;
SELECT TO_CHAR(100100100, '$999,999,999') FROM DUAL;
SELECT TO_CHAR(1100100100, '$999,999,999') FROM DUAL;
-- 10자리의 숫자라면 ############# (13)로 나온다
SELECT TO_CHAR(250000, '$999,999') FROM DUAL;
SELECT TO_CHAR(1250000, '$999,999') FROM DUAL;
-- 7자리 숫자를 입력하면 ######### (9)

-- TO_DATE
SELECT TO_DATE('20190617') FROM DUAL;
SELECT TO_DATE('20190610', 'YYYYMMDD') FROM DUAL;
SELECT TO_DATE('01172019', 'MMDDYYYY') FROM DUAL;

-- TO_NUMBER
SELECT TO_NUMBER ('100') + 12 FROM DUAL;

-- LAST_DAY
SELECT LAST_DAY(SYSDATE) FROM DUAL;
-- 이번달의 마지막날
SELECT LAST_DAY('2019-11-02') FROM DUAL;
-- 11월의 마지막날
SELECT LAST_DAY(TO_DATE('2019-11-01', 'YYYY-MM-DD')) FROM DUAL;
-- 11월의 마지막날

-- SUBSTRING(1, 3) "ABCDE" ->
-- SUBSTR
SELECT SUBSTR('ABCDE', 3) FROM DUAL;
-- 3번째부터 전부 가져온다
SELECT SUBSTR('ABCDE', 3, 1) FROM DUAL;
-- 3번째부터 1글자 가져온다

-- LENGTHB -> 문자길이 BYTE형식
-- LENGTH -> 문자길이
SELECT LENGTH('ABC') FROM DUAL;
SELECT LENGTH('ABCDEFG') FROM DUAL;

-- VARCHAR2(문자열) ->
-- DATE(날짜형식) -> VARCHAR2(문자열) : TO_CHAR

DROP TABLE TB_CHAR;
DROP TABLE TB_VARCHAR;
DROP TABLE TB_LONG;
DROP TABLE TB_NUMBER;
DROP TABLE TB_DATE;
DROP TABLE TB_INTEGER;




