DROP TABLE CUSTOMER
CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER(
	ID VARCHAR2(20) PRIMARY KEY,
	PWD VARCHAR2(50) NOT NULL,
	-- view에서 막아줘야지 DB까지 오면 안된다
	NAME VARCHAR2(50) NOT NULL,
	AGE NUMBER(10) NOT NULL,
	AUTH NUMBER(1) NOT NULL
	-- 우리가 구분하기 위해 존재하는 컬럼. 유저는 AUTH 값을 넣지 않는다
);

SELECT * FROM CUSTOMER;

