CREATE TABLE COFFEEORDER(
	SEQ NUMBER(10) PRIMARY KEY,
	CUS VARCHAR2(20) NOT NULL,
	-- 이 테이블에선 외래키이다 어디에 있나? CUSTOMER 테이블에

	COFF_TYPE VARCHAR(50) NOT NULL,
	COFF_SIZE NUMBER(10) NOT NULL,
	COFF_SYRUP VARCHAR2(10),
	COFF_SHOT VARCHAR2(10),
	COFF_WHIP VARCHAR2(10),
	COFF_TOTALPRICE NUMBER(10) NOT NULL
)

CREATE SEQUENCE SEQ_COFFEEORDER
START WITH 1
INCREMENT BY 1;

ALTER TABLE COFFEEORDER
ADD CONSTRAINT FK_COFFEEORDER_CUS FOREIGN KEY(CUS)
-- 여기서 CUS는 COFFEEORDER 테이블
REFERENCES COFFEECUSTOMER(ID);
-- 여기서 ID는 COFFEECUSTOMER 테이블


ALTER TABLE COFFEEORDER
ADD CONSTRAINT FK_COFFEEORDER_COFF_TYPE FOREIGN KEY(COFF_TYPE)
-- 여기서 COFF_TYPE은 COFFEEORDER 테이블
REFERENCES COFFEEPRICE(COFF_TYPE);
-- 여기서 COFF_TYPE은 COFFEEPRICE 테이블


SELECT * FROM COFFEEORDER;

DROP TABLE COFFEEORDER
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_COFFEEORDER;

