CREATE TABLE COFFEECUSTOMER(
	ID VARCHAR2(50) PRIMARY KEY,
	PASSWORD VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL
)

DROP TABLE COFFEECUSTOMER;

SELECT * FROM COFFEECUSTOMER;
