DROP TABLE YOUTUBE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_YOUTUBE;

CREATE TABLE YOUTUBE(
	SEQ NUMBER PRIMARY KEY,
	VNAME VARCHAR2(100) NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CATEGORY VARCHAR2(200) NOT NULL,
	WDATE DATE NOT NULL
);

ALTER TABLE YOUTUBE ADD CONSTRAINT
FK_YOUTUBE_MEM FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

CREATE SEQUENCE SEQ_YOUTUBE
START WITH 1
INCREMENT BY 1;

SELECT * FROM YOUTUBE